"""Compute the state of all 82 batches from the files on disk; optionally rewrite STATUS.md.

Usage: python status.py [--write] [--json]
States: done (final passes check_final) · adjudicated (final exists, guard fails) · keyed (A and B valid)
        · keyedA / keyedB (one valid keying) · pending
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_final import check
from common import N_BATCHES, ROOT, load_json
from validate import validate

PILOT = [2, 17, 27, 50]


def valid(path):
    return path.exists() and not validate(path)[0]


def batch_state(k):
    name = f"b{k:02d}"
    a = valid(ROOT / "keyA" / f"{name}.md")
    b = valid(ROOT / "keyB" / f"{name}.md")
    st = {"k": k, "name": name, "keyA": a, "keyB": b, "state": "pending"}
    if (ROOT / "final" / f"{name}.md").exists():
        res = check(k)
        st["state"] = "done" if res["pass"] else "adjudicated"
        if not res["pass"]:
            st["problems"] = res["problems"][:2]
    elif a and b:
        st["state"] = "keyed"
    elif a:
        st["state"] = "keyedA"
    elif b:
        st["state"] = "keyedB"
    rep = load_json(ROOT / "reports" / f"{name}.json")
    if rep and st["state"] == "done":
        st["agreement"] = rep["agreement"]
        st["unresolved"] = len(rep["unresolved_uncertain"])
        st["n_items"] = rep["n_items"]
        st["quran_residual"] = len(rep["quran_residual"])
    return st


def write_md(states):
    done = [s for s in states if s["state"] == "done"]
    agr = [s["agreement"] for s in done if "agreement" in s]
    lines = ["# STATUS — الدرر النقية transcription", "",
             f"Batches done: **{len(done)}/{N_BATCHES}**"
             + (f" · mean A/B agreement {sum(agr) / len(agr):.1%}" if agr else "")
             + f" · open uncertain spots: {sum(s.get('unresolved', 0) for s in done)}", "",
             "A batch is DONE iff `final\\bNN.md` exists, validates, and equals keyer A + the logged decisions "
             "(`scripts\\check_final.py`). This file is regenerated by `scripts\\status.py --write`.", "",
             "## How to resume (new session)", "",
             "1. Read `STATUS.md`, `CONVENTIONS.md`, `STRUCTURE.md`.",
             "2. `C:\\Python312\\python.exe scripts\\status.py --write` (re-validates every batch).",
             "3. Re-run the workflow: Workflow tool with `scriptPath: scripts/workflow.js` and "
             "`args: {\"batches\": [<numbers of the next ~10 not-done batches>]}`. Finished keyings and finished "
             "batches are skipped automatically.",
             "4. When all 82 are done: `scripts\\assemble.py`, then `scripts\\gen_docx.js` (see `README.md`).", "",
             "## Batches", "",
             "| Batch | Pages | State | Agreement | Items | Unresolved [؟] | Quran residual |",
             "|---|---|---|---|---|---|---|"]
    for s in states:
        k = s["k"]
        tag = " (pilot)" if k in PILOT else ""
        lines.append(f"| {s['name']}{tag} | {4 * k - 3}–{4 * k} | {s['state']} | "
                     + (f"{s['agreement']:.1%}" if "agreement" in s else "") + " | "
                     + str(s.get("n_items", "")) + " | " + str(s.get("unresolved", "")) + " | "
                     + str(s.get("quran_residual", "")) + " |")
    (ROOT / "STATUS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    states = [batch_state(k) for k in range(1, N_BATCHES + 1)]
    if "--write" in sys.argv:
        write_md(states)
    summary = {s2: [s["k"] for s in states if s["state"] == s2]
               for s2 in ("done", "adjudicated", "keyed", "keyedA", "keyedB", "pending")}
    summary["keyA_valid"] = [s["k"] for s in states if s["keyA"]]
    summary["keyB_valid"] = [s["k"] for s in states if s["keyB"]]
    if "--json" in sys.argv:
        print(json.dumps(summary))
    else:
        for key, v in summary.items():
            print(f"{key}: {len(v)} {v if len(v) <= 20 else ''}")


if __name__ == "__main__":
    main()
